src/Entity/Mouvies.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MouviesRepository")
 */
class Mouvies
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $popularity;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $vote_count;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $video;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster_path;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $adult;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $backdrop_path;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $original_language;

    /**
     * @ORM\Column(type="string", length=1406, nullable=true)
     */
    private $original_title;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $genre_ids = [];

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $vote_average;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $overview;

    /**
     * @ORM\Column(type="string", length=12, nullable=true)
     */
    private $release_date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPopularity(): ?float
    {
        return $this->popularity;
    }

    public function setPopularity(?float $popularity): self
    {
        $this->popularity = $popularity;

        return $this;
    }

    public function getVoteCount(): ?int
    {
        return $this->vote_count;
    }

    public function setVoteCount(?int $vote_count): self
    {
        $this->vote_count = $vote_count;

        return $this;
    }

    public function getVideo(): ?bool
    {
        return $this->video;
    }

    public function setVideo(?bool $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getPosterPath(): ?string
    {
        return $this->poster_path;
    }

    public function setPosterPath(?string $poster_path): self
    {
        $this->poster_path = $poster_path;

        return $this;
    }

    public function getAdult(): ?bool
    {
        return $this->adult;
    }

    public function setAdult(?bool $adult): self
    {
        $this->adult = $adult;

        return $this;
    }

    public function getBackdropPath(): ?string
    {
        return $this->backdrop_path;
    }

    public function setBackdropPath(?string $backdrop_path): self
    {
        $this->backdrop_path = $backdrop_path;

        return $this;
    }

    public function getOriginalLanguage(): ?string
    {
        return $this->original_language;
    }

    public function setOriginalLanguage(?string $original_language): self
    {
        $this->original_language = $original_language;

        return $this;
    }

    public function getOriginalTitle(): ?string
    {
        return $this->original_title;
    }

    public function setOriginalTitle(?string $original_title): self
    {
        $this->original_title = $original_title;

        return $this;
    }

    public function getGenreIds(): ?array
    {
        return $this->genre_ids;
    }

    public function setGenreIds(?array $genre_ids): self
    {
        $this->genre_ids = $genre_ids;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getVoteAverage(): ?float
    {
        return $this->vote_average;
    }

    public function setVoteAverage(?float $vote_average): self
    {
        $this->vote_average = $vote_average;

        return $this;
    }

    public function getOverview(): ?string
    {
        return $this->overview;
    }

    public function setOverview(?string $overview): self
    {
        $this->overview = $overview;

        return $this;
    }

    public function getReleaseDate(): ?string
    {
        return $this->release_date;
    }

    public function setReleaseDate(?string $release_date): self
    {
        $this->release_date = $release_date;

        return $this;
    }
    public function __toString(): string
    {
        return $this->original_title;
    }
}

src/Form/MouviesType.php
<?php

namespace App\Form;

use App\Entity\Mouvies;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MouviesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('popularity')
            ->add('vote_count')
            ->add('video')
            ->add('poster_path')
            ->add('adult')
            ->add('backdrop_path')
            ->add('original_language')
            ->add('original_title')
            ->add('genre_ids')
            ->add('title')
            ->add('vote_average')
            ->add('overview')
            ->add('release_date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Mouvies::class,
        ]);
    }
}

src/Controller/MouviesController.php
<?php

namespace App\Controller;

use App\Entity\Mouvies;
use App\Form\MouviesType;
use App\Repository\MouviesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/mouvies")
 */
class MouviesController extends AbstractController
{
    /**
     * @Route("/", name="mouvies_index", methods={"GET"})
     */
    public function index(MouviesRepository $mouviesRepository): Response
    {
        $this ->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('mouvies/index.html.twig', [
            'mouvies' => $mouviesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="mouvies_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $this ->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $mouvy = new Mouvies();
        $form = $this->createForm(MouviesType::class, $mouvy);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($mouvy);
            $entityManager->flush();

            return $this->redirectToRoute('mouvies_index');
        }

        return $this->render('mouvies/new.html.twig', [
            'mouvy' => $mouvy,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="mouvies_show", methods={"GET"})
     */
    public function show(Mouvies $mouvy): Response
    {
        $this ->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        return $this->render('mouvies/show.html.twig', [
            'user' => $this->getUser(),
            'mouvy' => $mouvy,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="mouvies_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Mouvies $mouvy): Response
    {
        $this ->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $form = $this->createForm(MouviesType::class, $mouvy);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('mouvies_index');
        }

        return $this->render('mouvies/edit.html.twig', [
            'mouvy' => $mouvy,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="mouvies_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Mouvies $mouvy): Response
    {
        $this ->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->isCsrfTokenValid('delete'.$mouvy->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($mouvy);
            $entityManager->flush();
        }

        return $this->redirectToRoute('mouvies_index');
    }

    //contrôler le nombre de mouvies affichés par page
    public function mouvieSortAction($page, MouviesRepository $mouviesRepository)
    {  
        $maxMouvies ='10';
        $em = $this->getDoctrine()->getManager();
        $mouviesCount = $mouviesRepository->countTotal();
        $mouviesOfPage = $mouviesRepository->getListMouvie($page, $maxMouvies);
        $pagination = array(
                'page' => $page,
                'route' => 'mouvie_list',
                'pages_count' => ceil($mouviesCount / $maxMouvies),
                'route_params' => array()
        );

            return $this->render('mouvies/index.html.twig', array(
                'title' => "coucou",
                'mouvies' => $mouviesOfPage,
                'posts_count'=>$mouviesCount,
                'pagination'=> $pagination
                ));
    }
}

templates/mouvies/_delete_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}_DELETE_Mouvies{% endblock %}

{% block body %}
<form method="post" action="{{ path('mouvies_delete', {'id': mouvy.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mouvy.id) }}">
    <button class="btn">Delete</button>
</form>
{% endblock %}

templates/mouvies/_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}form_start{% endblock %}

{% block body %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}
{% endblock %}

templates/mouvies/adminShow.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mouvies{% endblock %}

{% block body %}
    <h1>Mouvies</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mouvy.id }}</td>
            </tr>
            <tr>
                <th>Popularity</th>
                <td>{{ mouvy.popularity }}</td>
            </tr>
            <tr>
                <th>Vote_count</th>
                <td>{{ mouvy.voteCount }}</td>
            </tr>
            <tr>
                <th>Video</th>
                <td>{{ mouvy.video ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Poster_path</th>
                <td>{{ mouvy.posterPath }}</td>
            </tr>
            <tr>
                <th>Adult</th>
                <td>{{ mouvy.adult ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Backdrop_path</th>
                <td>{{ mouvy.backdropPath }}</td>
            </tr>
            <tr>
                <th>Original_language</th>
                <td>{{ mouvy.originalLanguage }}</td>
            </tr>
            <tr>
                <th>Original_title</th>
                <td>{{ mouvy.originalTitle }}</td>
            </tr>
            <tr>
                <th>Genre_ids</th>
                <td>{{ mouvy.genreIds ? mouvy.genreIds|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ mouvy.title }}</td>
            </tr>
            <tr>
                <th>Vote_average</th>
                <td>{{ mouvy.voteAverage }}</td>
            </tr>
            <tr>
                <th>Overview</th>
                <td>{{ mouvy.overview }}</td>
            </tr>
            <tr>
                <th>Release_date</th>
                <td>{{ mouvy.releaseDate }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('mouvies_index') }}">back to list</a>

    <a href="{{ path('mouvies_edit', {'id': mouvy.id}) }}">Modifier</a>

    {{ include('mouvies/_delete_form.html.twig') }}
{% endblock %}

templates/mouvies/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Mouvies{% endblock %}

{% block body %}
    <h1>Edit Mouvies</h1>

    {{ include('mouvies/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    <a href="{{ path('mouvies_index') }}">back to list</a>

    {{ include('mouvies/_delete_form.html.twig') }}
{% endblock %}

templates/mouvies/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mouvies index{% endblock %}

{% block body %}
    <h1>Mouvies index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Popularity</th>
                <th>Poster_path</th>
                <th>Adult</th>
                <th>Original_language</th>
                <th>Original_title</th>
                <th>Genre_ids</th>
                <th>Release_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for mouvy in mouvies %}
            <tr>
                <td>{{ mouvy.popularity }}</td>
                <td>{{ mouvy.posterPath }}</td>
                <td>{{ mouvy.adult ? 'Yes' : 'No' }}</td>
                <td>{{ mouvy.originalLanguage }}</td>
                <td>{{ mouvy.originalTitle }}</td>
                <td>{{ mouvy.genreIds ? mouvy.genreIds|join(', ') : '' }}</td>
                <td>{{ mouvy.releaseDate }}</td>
                <td>
                    <a href="{{ path('mouvies_show', {'id': mouvy.id}) }}">More</a>
                    <a href="{{ path('mouvies_edit', {'id': mouvy.id}) }}">Modifier</a>
                 </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="15">no records found</td>
            </tr>
        {% endfor %}


        <div class="pagination">
    <div class="pagination-buttons link_blog text-center">
    {% if pagination.page>1 %}
       <a href="{{ path(pagination.route, pagination.route_params|merge({'page': 1})) }}"></a>
       <a href="{{ path(pagination.route, pagination.route_params|merge({'page': pagination.page-1,})) }}"><a>
    {% endif %}

    {% if posts_count!=0 %}
       {% for p in range(max(pagination.page-2, 1), min(pagination.page+2, pagination.pages_count)) %}
          <a{% if p == pagination.page %} class="current-page"
          {% endif %} 
          href="{{ path(pagination.route, pagination.route_params|merge({'page': p})) }}">{{ p }}</a>
       {% endfor %}
    {% endif %}

    {% if pagination.page<pagination.pages_count %}
       <a href="{{ path(pagination.route, pagination.route_params|merge({'page': pagination.page+1})) }}">></a>
       <a href="{{ path(pagination.route, pagination.route_params|merge({'page': pagination.pages_count})) }}">>></a>
    {% endif %}
    </div>
</div>
        </tbody>
    </table>

    <a href="{{ path('mouvies_new') }}">Create new</a>
{% endblock %}

templates/mouvies/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Mouvies{% endblock %}

{% block body %}
    <h1>Create new Mouvies</h1>

    {{ include('mouvies/_form.html.twig') }}

    <a href="{{ path('mouvies_index') }}">back to list</a>
{% endblock %}

templates/mouvies/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mouvies{% endblock %}

{% block body %}
    <h1>Mouvies</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Popularity</th>
                <td>{{ mouvy.popularity }}</td>
            </tr>
            <tr>
                <th>Vote_count</th>
                <td>{{ mouvy.voteCount }}</td>
            </tr>
            <tr>
                <th>Video</th>
                <td>{{ mouvy.video ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Poster_path</th>
                <td>{{ mouvy.posterPath }}</td>
            </tr>
            <tr>
                <th>Adult</th>
                <td>{{ mouvy.adult ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Original_language</th>
                <td>{{ mouvy.originalLanguage }}</td>
            </tr>
            <tr>
                <th>Original_title</th>
                <td>{{ mouvy.originalTitle }}</td>
            </tr>
            <tr>
                <th>Genre_ids</th>
                <td>{{ mouvy.genreIds ? mouvy.genreIds|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Overview</th>
                <td>{{ mouvy.overview }}</td>
            </tr>
            <tr>
                <th>Release_date</th>
                <td>{{ mouvy.releaseDate }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('mouvies_index') }}">back to list</a>
     {% for mylist in user.yes %}
      <br>
        <a href="{{ path('add_mouvie_to_list', {'id ': mylist.id, 'idMouvie':mouvy.id })}}">Ajouter à la liste {{mylist.name}}</a>
       
     {% endfor %}
      <br>
    <a href="{{ path('mouvies_edit', {'id':mouvy.id }) }}">Modifier</a>

    {{ include('mouvies/_delete_form.html.twig') }}
{% endblock %}